import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Providers from "@/lib/providers/Providers";
import Header from "./components/UI/Headers/Header";

const chillax = localFont({
  src: "../../public/fonts/Chillax.woff2",
  variable: "--font-chillax",
});

export const metadata: Metadata = {
  title: "TouhidCodes Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body className={chillax.className}>
          <Header />
          {children}
        </body>
      </html>
    </Providers>
  );
}
