import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const chillax = localFont({
  src: "../../public/fonts/Chillax.woff2",
  variable: "--font-chillax",
});

export const metadata: Metadata = {
  title: "TouhidCodes Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={chillax.className}>{children}</body>
    </html>
  );
}
